blank_issues_enabled: true
contact_links:
  - name: Awesome Ford Transit Discussion on FTUSA Forum
    url: https://www.fordtransitusaforum.com/threads/awesome-ford-transit-list.90243/
    about: Please ask and answer questions on the Forum.
